// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddArt: typeof import('./../src/components/article/AddArt.vue')['default']
    ArtList: typeof import('./../src/components/article/ArtList.vue')['default']
    CateList: typeof import('./../src/components/category/CateList.vue')['default']
    CommentList: typeof import('./../src/components/comment/commentList.vue')['default']
    Cover: typeof import('./../src/components/cover.vue')['default']
    Editor: typeof import('./../src/components/editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./../src/components/admin/Footer.vue')['default']
    Header: typeof import('./../src/components/admin/Header.vue')['default']
    Index: typeof import('./../src/components/admin/Index.vue')['default']
    LeftBar: typeof import('./../src/components/leftBar.vue')['default']
    MdEditor: typeof import('./../src/components/MdEditor.vue')['default']
    Nav: typeof import('./../src/components/admin/Nav.vue')['default']
    Profile: typeof import('./../src/components/user/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideDrawer: typeof import('./../src/components/sideDrawer.vue')['default']
    TheMenu: typeof import('./../src/components/theMenu.vue')['default']
    Timeline: typeof import('./../src/components/Timeline.vue')['default']
    UserList: typeof import('./../src/components/user/UserList.vue')['default']
    Vis: typeof import('./../src/components/Vis.vue')['default']
    VueWxlogin: typeof import('./../src/components/wxLogin/vue-wxlogin.vue')['default']
    Wave: typeof import('./../src/components/wave.vue')['default']
  }
}
