// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cover: typeof import('./../src/components/cover.vue')['default']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LeftBar: typeof import('./../src/components/leftBar.vue')['default']
    MdEditor: typeof import('./../src/components/MdEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./../src/components/Timeline.vue')['default']
    Vis: typeof import('./../src/components/Vis.vue')['default']
    VueWxlogin: typeof import('./../src/components/wxLogin/vue-wxlogin.vue')['default']
    Wave: typeof import('./../src/components/wave.vue')['default']
  }
}
